/**
 * SmartLink Slip Service
 *
 * Persists and validates generated identity slips via Supabase / Turso backend API.
 */

import {
  GeneratedSlipRecord,
  SlipFormatType,
  StandardizedVerificationResult,
} from "../types/verification";
import { safeFetchJson } from "../utils/authErrorHandler";

export class SlipService {
  /**
   * Helper to generate a secure random verification token for QR codes
   */
  static generateSecureToken(serviceType: string, idNumber: string): string {
    const randomHex = Array.from(crypto.getRandomValues(new Uint8Array(12)))
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("");
    return `SLIP-${serviceType.toUpperCase()}-${idNumber.substring(0, 4)}-${randomHex}`;
  }

  /**
   * Create and persist a new generated slip
   */
  static async saveSlipFromVerification(params: {
    userId: string;
    userEmail?: string;
    verificationResult: StandardizedVerificationResult;
    formatType: SlipFormatType;
  }): Promise<GeneratedSlipRecord> {
    const { userId, userEmail, verificationResult, formatType } = params;
    const { data, reference, providerName, verifiedId, maskedId, service } = verificationResult;

    const slipId = `slip_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
    const qrToken = this.generateSecureToken(service || "NIN", verifiedId || "0000");

    const origin = typeof window !== "undefined" && window.location?.origin
      ? window.location.origin
      : "https://smartlinkdigital.ng";
    const qrVerificationUrl = `${origin}/verify/slip/${qrToken}`;

    const nowISO = new Date().toISOString();

    const slipRecord: GeneratedSlipRecord = {
      id: slipId,
      slipId,
      userId,
      userEmail: userEmail || undefined,
      serviceType: service || "NIN",
      formatType,
      identificationNumber: verifiedId,
      maskedId,
      trackingId: data?.rawFields?.trackingId || `20TO${verifiedId.substring(0, 4)}000008J`,
      qrVerificationToken: qrToken,
      qrVerificationUrl,
      holderData: {
        fullName: data?.fullName || "RECORD CONFIRMED",
        surname: data?.lastName || data?.fullName?.split(" ")[0] || "",
        firstName: data?.firstName || data?.fullName?.split(" ")[1] || "",
        middleName: data?.middleName || data?.fullName?.split(" ").slice(2).join(" ") || "",
        gender: data?.gender || "M",
        dateOfBirth: data?.dateOfBirth || "",
        issueDate: nowISO,
        address: data?.address || "FEDERAL RESIDENTIAL REGISTRY",
        stateOfOrigin: data?.stateOfOrigin || "",
        lga: data?.lga || "",
        phoneNumber: data?.phoneNumber || "",
        email: data?.email || "",
        photoUrl: data?.photoUrl || "",
        nin: verifiedId,
        bvn: data?.bvn,
      },
      reference,
      providerName,
      createdAt: nowISO,
      status: "ACTIVE",
    };

    try {
      await safeFetchJson("/api/verification/slips", {
        method: "POST",
        body: JSON.stringify(slipRecord),
      });
    } catch (err) {
      console.warn("[SlipService] Local slip save notification:", err);
    }

    return slipRecord;
  }

  /**
   * Fetch a slip by its Slip ID
   */
  static async getSlipById(slipId: string): Promise<GeneratedSlipRecord | null> {
    try {
      const res = await safeFetchJson(`/api/verification/slips/${encodeURIComponent(slipId)}`);
      if (res.ok && res.data?.slip) {
        return res.data.slip;
      }
    } catch (err) {
      console.error("[SlipService] Error retrieving slip by ID:", err);
    }
    return null;
  }

  /**
   * Fetch all slips generated by a specific user
   */
  static async getUserSlips(userId: string): Promise<GeneratedSlipRecord[]> {
    if (!userId) return [];
    try {
      const res = await safeFetchJson(`/api/verification/slips?userId=${encodeURIComponent(userId)}`);
      if (res.ok && Array.isArray(res.data?.slips)) {
        return res.data.slips;
      }
    } catch (err) {
      console.warn("[SlipService] Error fetching user slips:", err);
    }
    return [];
  }
}

// Backwards compatibility alias
export const StorageSlipService = SlipService;
